name: Test Raccoon Java Client
on:
  push:
    paths:
      - "clients/java/**"
    branches:
      - main
  pull_request:
    paths:
      - "clients/java/**"
    branches:
      - main
jobs:
  test-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Grant execute permission for gradlew
        working-directory: clients/java
        run: chmod +x gradlew
      - name: Test
        working-directory: clients/java
        run: ./gradlew test